# Generated by Django 4.1.5 on 2023-03-08 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed',
            field=models.ManyToManyField(through='flux.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
