# Generated by Django 4.1.5 on 2023-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(blank=True, max_length=8192, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
